{
 "title": "Mikrotik",
 "description": "Mikrotik snmp monitoring (prometheus)",
 "tags": [
  "prometheus",
  "Mikrotik",
  "snmp",
  "snmp v3",
  "snmp_exporter"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "Job",
    "query": {
     "query": "label_values(ifHCInOctets,  job)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(mtxrInterfaceStatsIndex,instance)"
    }
   },
   {
    "name": "index",
    "query": {
     "query": "label_values(ifHighSpeed{instance='$instance'},ifIndex)"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "query_result(sort(mtxrInterfaceStatsIndex{ifName=~'^(ether).+',instance='$instance'}) or sort(mtxrInterfaceStatsIndex{ifName=~'^(sfp|wlan).+',instance='$instance'}) or sort(mtxrInterfaceStatsIndex{ifName=~'^bridge.+',instance='$instance'}) or  sort(mtxrInterfaceStatsIndex{ifName!~'^(ether|bridge).+',instance='$instance'}) )"
    }
   },
   {
    "name": "desc",
    "query": {
     "query": "query_result(ifHCInOctets{ifName=\"$Interface\",instance=\"$instance\"})"
    }
   },
   {
    "name": "queuesimple_name",
    "query": {
     "query": "query_result((mtxrQueueSimplePacketsIn * on (mtxrQueueSimpleIndex) group_left(mtxrQueueSimpleName) mtxrQueueSimpleName{instance='$instance',}))"
    }
   },
   {
    "name": "queuetree_name",
    "query": {
     "query": "query_result((mtxrQueueTreePackets * on (mtxrQueueTreeIndex) group_left(mtxrQueueTreeName) mtxrQueueTreeName{instance='$instance',}))"
    }
   },
   {
    "name": "queuetree_parent",
    "query": {
     "query": "query_result((mtxrQueueTreeParentIndex * on (mtxrQueueTreeIndex) group_left(mtxrQueueTreeName) mtxrQueueTreeName{instance='$instance',}))"
    }
   },
   {
    "name": "queuetree_flow",
    "query": {
     "query": "query_result((mtxrQueueTreeParentIndex * on (mtxrQueueTreeName) group_left(mtxrQueueTreeIndex) mtxrQueueTreeIndex{instance='$instance',}))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Total",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(hrProcessorLoad{instance='$instance'})"
    }
   ]
  },
  {
   "title": "Load RAM",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(hrStorageUsed{hrStorageIndex='65536',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='65536',instance='$instance'})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "hrSystemUptime{instance='$instance'}/100"
    }
   ]
  },
  {
   "title": "CPU Mhz",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "MHz" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrHlProcessorFrequency{instance='$instance'}"
    }
   ]
  },
  {
   "title": "System",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "avg(hrProcessorLoad{instance='$instance'})",
     "legendFormat": "Load CPU {{hrDeviceIndex}} "
    },
    {
     "expr": "(hrStorageUsed{hrStorageIndex='65536',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='65536',instance='$instance'})",
     "legendFormat": "RAM usage"
    },
    {
     "expr": "(hrStorageUsed{hrStorageIndex='131072',instance='$instance'} * 100 )/(hrStorageSize{hrStorageIndex='131072',instance='$instance'})",
     "legendFormat": "System disk"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "timeseries",
   "description": "Showing values > 0",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
     "legendFormat": "In - {{ifName}}"
    },
    {
     "expr": "irate(ifHCOutOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
     "legendFormat": "Out - {{ifName}}"
    }
   ]
  },
  {
   "title": "Interfaces Traffic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Traffic \"$Interface\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 14 },
   "repeat": "Interface",
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "irate(ifHCOutOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
     "legendFormat": "Download"
    },
    {
     "expr": "irate(ifHCInOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
     "legendFormat": "Upload"
    }
   ]
  }
 ]
}